// svelte/src/lib/TodoForm.svelte
<script>
  import { createEventDispatcher } from "svelte";


    let todoValue = ""
    const dispatcher = createEventDispatcher()
    function handleSubmit(e)
    {
        dispatcher("onSubmit", todoValue)
    }
</script>

<form on:submit|preventDefault={handleSubmit}>
<input type="text" bind:value={todoValue} />
<button type="submit"> Add Todo</button>
</form>

// vue/src/components/TodoForm.vue
<template>
    <form @submit.prevent="handleSubmit">
        <input type="text" v-model="todoValue">
        <button type="submit">Add Todo</button>
    </form>
</template>

<script setup>
import {ref} from "vue"
const emit = defineEmits(['onSubmit'])

const todoValue = ref("")

function handleSubmit(e)
{
    emit("onSubmit", todoValue.value)
}
</script>
