// vue/src/components/TodoList.vue
<template>
    <div>
        <TodoForm @onSubmit="addTodo" />
        <ul>
            <TodoItem v-for="(item, index) in todos" :key="index" :todoItem="item" />
        </ul>
    </div>
</template>

<script setup>
import {ref} from "vue"
import TodoForm from "./TodoForm.vue"
import TodoItem from "./TodoItem.vue"
const todos = ref([{id: 1, text: "Learn Svelte"}])

function addTodo(value)
{
    todos.value = [...todos.value, {id: todos.value.length + 1, text: value}]
}
</script>

// svelte/src/lib/TodoList.svelte
<script>
  import TodoForm from "./TodoForm.svelte";
import TodoItem from "./TodoItem.svelte";

    let todos = [{id: 1, text: "Learn React"}]

    function addTodo(e)
    {
        const newTodos = [...todos, {id: todos.length + 1, text: e.detail}]
        todos = newTodos
    }
</script>

<TodoForm on:onSubmit={addTodo} />
<ul>
    {#each todos as todo(todo.id)}
        <TodoItem todoItem={todo} />
    {/each}
</ul>
