// svelte/src/lib/TodoForm.svelte
<script>
  import { createEventDispatcher } from "svelte";


    let todoValue = ""
    const dispatcher = createEventDispatcher()
    function handleSubmit(e)
    {
        dispatcher("onSubmit", todoValue)
    }
</script>

<form on:submit|preventDefault={handleSubmit}>
<input type="text" bind:value={todoValue} />
<button type="submit"> Add Todo</button>
</form>

// react/src/components/TodoForm.jsx
import { useState } from 'react'

export default function TodoForm({onSubmit}) {
  const [todoValue, setTodoValue] = useState("")

  function handleSubmit(e)
  {
    e.preventDefault()
    onSubmit(todoValue)
  }

  return (
    <form onSubmit={handleSubmit}>
        <input type="text" value={todoValue} onInput={(e)=>setTodoValue(e.target.value)} />
        <button type="submit">Add Todo</button>
    </form>
  )
}
