// vue/src/components/TodoList.vue
<template>
    <div>
        <TodoForm @onSubmit="addTodo" />
        <ul>
            <TodoItem v-for="(item, index) in todos" :key="index" :todoItem="item" />
        </ul>
    </div>
</template>

<script setup>
import {ref} from "vue"
import TodoForm from "./TodoForm.vue"
import TodoItem from "./TodoItem.vue"
const todos = ref([{id: 1, text: "Learn Svelte"}])

function addTodo(value)
{
    todos.value = [...todos.value, {id: todos.value.length + 1, text: value}]
}
</script>

// react/src/components/TodoList.jsx
import React, { useState } from 'react'
import TodoForm from './TodoForm'
import TodoItem from './TodoItem'

export default function TodoList() {
   
    const [todos, setTodos] = useState([{id: 1, text: "Learn Vue"}])
    
    function addTodo(value)
    {
        setTodos((prevTodos)=>([...prevTodos, {id: prevTodos.length+1, text:value}]))
    }

  return (
    <>
        <TodoForm onSubmit={addTodo} />
        <ul>
            {todos.map((item, index) => <TodoItem todoItem={item} key={index} /> )}
        </ul>
    </>
  )
}
